'use strict';
const definition=JSON.parse(document.getElementById('definition').textContent);
const storageKey='yoruba-new-models-001:'+definition.items.flatMap(s=>s.ai_generations.map(g=>g.audio_sha256)).join(':');
const labels={lexical_tone_realization:'Lexical-tone realization',segmental_pronunciation:'Segmental pronunciation',perceived_nasality:'Perceived nasality',prosody_intonation:'Prosody/intonation',rhythm_fluency:'Rhythm/fluency',overall_yoruba_naturalness:'Overall Yoruba naturalness',reviewer_confidence:'Reviewer confidence'};
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const intervalControls='<p><small>Optional problematic intervals (seconds). Start must be less than end; end must not exceed this recording’s duration.</small></p><div class="intervals"></div><button type="button" class="add-interval">Add time interval</button>';
for(const s of definition.items){
 const article=document.createElement('article');article.dataset.sentence=s.sentence_id;
 const players=[['Natural reference',s.natural_audio_url,s.natural_duration_s],...s.ai_generations.map(g=>[g.model_snapshot+' · take '+g.repeat_generation_id,g.audio_url,g.duration_s])].map(([name,url,duration])=>`<div><h3>${name}</h3><audio controls preload="none" src="${escapeHTML(url)}"></audio><small>${duration.toFixed(3)} seconds</small></div>`).join('');
 const forms=s.ai_generations.map(g=>`<fieldset class="annotation ai" data-generation="${g.ai_generation_id}" data-duration="${g.duration_s}"><legend>AI generation ${g.repeat_generation_id} · ${g.ai_generation_id}</legend><small>${escapeHTML(g.model_snapshot)} · ${escapeHTML(g.voice)}</small>${Object.entries(definition.rating_options).map(([key,values])=>`<label>${labels[key]}<select data-rating="${key}"><option value="">Not reviewed</option>${values.map(v=>`<option value="${escapeHTML(v)}">${escapeHTML(v)}</option>`).join('')}</select></label>`).join('')}<p>Optional issue tags</p><div class="tags">${definition.issue_tags.map(t=>`<label><input type="checkbox" data-tag="${escapeHTML(t)}"> ${escapeHTML(t)}</label>`).join('')}</div><label>Free-text notes<textarea class="notes"></textarea></label>${intervalControls}</fieldset>`).join('');
 article.innerHTML=`<h2>Sentence ${s.sentence_id.slice(1)}</h2><p class="text" lang="yo">${escapeHTML(s.exact_text)}</p><p>${s.source_clip_id} · ${s.speaker_id}</p><div class="players">${players}</div><section class="annotation natural" data-duration="${s.natural_duration_s}"><h3>Natural-reference observations (optional)</h3><label>Notes about the natural reference<textarea class="notes"></textarea></label>${intervalControls}</section><div class="forms">${forms}</div>`;
 document.getElementById('items').appendChild(article);
}
function addInterval(section,value={start_s:'',end_s:'',notes:''}){
 const row=document.createElement('div');row.className='interval';row.innerHTML='<label>Start (s)<input class="start" type="number" min="0" step="any"></label><label>End (s)<input class="end" type="number" min="0" step="any"></label><label>Interval notes<input class="interval-notes"></label><button type="button" class="remove-interval">Remove</button>';
 row.querySelector('.start').value=value.start_s??'';row.querySelector('.end').value=value.end_s??'';row.querySelector('.interval-notes').value=value.notes??'';section.querySelector('.intervals').appendChild(row);
}
function readSection(section,validate=false){
 const ratings=Object.fromEntries([...section.querySelectorAll('[data-rating]')].map(e=>[e.dataset.rating,e.value||null]));
 const tags=[...section.querySelectorAll('[data-tag]:checked')].map(e=>e.dataset.tag);
 const intervals=[...section.querySelectorAll('.interval')].map(row=>{const a=row.querySelector('.start').value,b=row.querySelector('.end').value;return {start_s:a===''?null:Number(a),end_s:b===''?null:Number(b),notes:row.querySelector('.interval-notes').value};});
 if(validate)for(const i of intervals)if(i.start_s===null||i.end_s===null||!Number.isFinite(i.start_s)||!Number.isFinite(i.end_s)||i.start_s<0||i.end_s<=i.start_s||i.end_s>Number(section.dataset.duration))throw new Error('Invalid interval in '+(section.dataset.generation||section.closest('article').dataset.sentence+' natural reference')+'. Use 0 ≤ start < end ≤ recording duration.');
 const notes=section.querySelector('.notes').value;
 const touched=Object.values(ratings).some(v=>v!==null)||tags.length>0||notes.length>0||intervals.length>0;
 return {ratings,issue_tags:tags,notes,problematic_time_intervals:intervals,annotation_timestamp:touched?(section.dataset.updated||null):null,review_status:!touched?'not_reviewed':Object.keys(ratings).length&&Object.values(ratings).every(v=>v!==null)?'dimensions_completed':'partial'};
}
function payload(validate=false){
 const reviewer=document.getElementById('reviewer').value.trim();if(validate&&!reviewer)throw new Error('Enter a reviewer identifier before exporting.');
 return {review_version:1,review_session_id:"paired_new_models_001",confidence_definition:"certainty about what was heard and the selected judgment, not certainty about technical/acoustic cause",schema_version:definition.schema_version,study_type:definition.study_type,evidence_type:'human_native_listener_perception_not_acoustic_diagnosis',reviewer_identifier:reviewer||null,export_timestamp:new Date().toISOString(),dimensions_combined:false,training_use:false,items:definition.items.map(s=>{
  const article=document.querySelector(`[data-sentence="${s.sentence_id}"]`);
  return {sentence_id:s.sentence_id,source_clip_id:s.source_clip_id,exact_yoruba_text:s.exact_text,natural_reference:{reviewer_identifier:reviewer||null,sentence_id:s.sentence_id,source_clip_id:s.source_clip_id,speaker_id:s.speaker_id,audio_sha256:s.natural_audio_sha256,...readSection(article.querySelector('.natural'),validate)},ai_annotations:s.ai_generations.map(g=>({reviewer_identifier:reviewer||null,sentence_id:s.sentence_id,source_clip_id:s.source_clip_id,ai_generation_id:g.ai_generation_id,repeat_generation_id:g.repeat_generation_id,provider:g.provider,model_snapshot:g.model_snapshot,voice:g.voice,voice_version:g.voice_version,audio_sha256:g.audio_sha256,...readSection(article.querySelector(`[data-generation="${g.ai_generation_id}"]`),validate)}))};})};
}
function save(){try{localStorage.setItem(storageKey,JSON.stringify(payload()));document.getElementById('status').textContent='Draft saved in this browser. Export Review JSON to keep a portable copy.';}catch{document.getElementById('status').textContent='Browser draft storage unavailable. Keep this page open and export JSON before closing.';}}
function changed(event){const section=event.target.closest('.annotation');if(section)section.dataset.updated=new Date().toISOString();save();}
document.addEventListener('input',changed);document.addEventListener('change',changed);
document.addEventListener('click',event=>{if(event.target.matches('.add-interval')){addInterval(event.target.closest('.annotation'));changed(event);}if(event.target.matches('.remove-interval')){const section=event.target.closest('.annotation');event.target.closest('.interval').remove();section.dataset.updated=new Date().toISOString();save();}});
function restoreSection(section,value){for(const [k,v] of Object.entries(value.ratings||{})){const e=section.querySelector(`[data-rating="${k}"]`);if(e)e.value=v||'';}for(const e of section.querySelectorAll('[data-tag]'))e.checked=(value.issue_tags||[]).includes(e.dataset.tag);section.querySelector('.notes').value=value.notes||'';for(const i of value.problematic_time_intervals||[])addInterval(section,i);section.dataset.updated=value.annotation_timestamp||'';}
try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(saved){document.getElementById('reviewer').value=saved.reviewer_identifier||'';for(const s of saved.items||[]){const article=document.querySelector(`[data-sentence="${s.sentence_id}"]`);if(!article)continue;restoreSection(article.querySelector('.natural'),s.natural_reference);for(const a of s.ai_annotations||[]){const section=article.querySelector(`[data-generation="${a.ai_generation_id}"]`);if(section)restoreSection(section,a);}}document.getElementById('status').textContent='Saved draft restored. Export JSON when ready.';}}catch{document.getElementById('status').textContent='Could not restore a draft. Export JSON before closing.';}
document.querySelectorAll('audio').forEach(a=>a.addEventListener('play',()=>document.querySelectorAll('audio').forEach(b=>{if(a!==b)b.pause();})));
document.getElementById('export').onclick=()=>{try{const result=payload(true);save();const u=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='paired_new_models_001.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);document.getElementById('status').textContent='Review JSON exported. Unreviewed dimensions remain null; no combined score.';}catch(e){document.getElementById('status').textContent=e.message;}};

const baselineAudio={"p01": [{"url": "../paired-ai-001/audio/p01_coral_r01.wav", "repeat": 1}, {"url": "../paired-ai-001/audio/p01_coral_r02.wav", "repeat": 2}], "p02": [{"url": "../paired-ai-001/audio/p02_coral_r01.wav", "repeat": 1}, {"url": "../paired-ai-001/audio/p02_coral_r02.wav", "repeat": 2}], "p03": [{"url": "../paired-ai-001/audio/p03_coral_r01.wav", "repeat": 1}, {"url": "../paired-ai-001/audio/p03_coral_r02.wav", "repeat": 2}], "p04": [{"url": "../paired-ai-001/audio/p04_coral_r01.wav", "repeat": 1}, {"url": "../paired-ai-001/audio/p04_coral_r02.wav", "repeat": 2}], "p05": [{"url": "../paired-ai-001/audio/p05_coral_r01.wav", "repeat": 1}, {"url": "../paired-ai-001/audio/p05_coral_r02.wav", "repeat": 2}], "p06": [{"url": "../paired-ai-001/audio/p06_coral_r01.wav", "repeat": 1}, {"url": "../paired-ai-001/audio/p06_coral_r02.wav", "repeat": 2}]}; for(const [sid,clips] of Object.entries(baselineAudio)){const box=document.createElement("section");box.innerHTML="<h3>Existing gpt-4o-mini-tts / coral baseline (accepted v2 review preserved)</h3>"+clips.map(c=>`<p>Take ${c.repeat}</p><audio controls preload="none" src="${c.url}"></audio>`).join("");document.querySelector(`[data-sentence="${sid}"]`).appendChild(box);}
