"""Separate first-pass listening form; preserve technical alignment and all audio."""
import hashlib,json,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'work/slr86/p03-listening-001';SOURCE=ROOT/'work/slr86/p03-supervised-001'
def main():
 OUT.mkdir(exist_ok=True);raw=(SOURCE/'annotation_package.json').read_bytes();data=json.loads(raw)
 data['technical_package_sha256']=hashlib.sha256(raw).hexdigest();data['technical_package_path']='../p03-supervised-001/annotation_package.json'
 for r in data['records']:
  # Both review directories share the same parent; original audio links remain valid.
  r['spectrogram_url']='../p03-supervised-001/'+r['spectrogram_url']
 html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>p03 · Yorùbá listening review</title><style>
body{font:18px system-ui;background:#f3f6f8;color:#172c3b;max-width:1000px;margin:auto;padding:24px}header,article{background:white;border:1px solid #d5dfe5;border-radius:14px;padding:24px;margin-bottom:20px}h1{font-size:30px}h2{font-size:24px}.yoruba{font-size:27px;line-height:1.6}button,input,textarea{font:inherit}button{padding:10px 16px;cursor:pointer;border-radius:8px;border:1px solid #718da2;background:white}button.primary{background:#145e78;color:white}button:disabled{opacity:.5;cursor:default}audio{width:100%;margin:12px 0}fieldset{border:0;padding:0;margin:22px 0}legend{font-weight:600;margin-bottom:10px}.choices{display:flex;gap:10px;flex-wrap:wrap}.choice{padding:10px;border:1px solid #cdd8df;border-radius:8px;cursor:pointer}.choice:has(input:checked){background:#e6f3f8;border-color:#145e78}textarea{width:100%;box-sizing:border-box;min-height:90px;padding:12px}.cut{display:block;background:#fff2d6;padding:14px;border-radius:8px;margin:18px 0}.muted{color:#526876;font-size:16px}.navigation{display:flex;justify-content:space-between;gap:12px;margin-top:20px}#status{background:#e8f2f6;padding:12px;border-radius:8px}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.tabs button[aria-pressed=true]{background:#145e78;color:white}input[type=text]{padding:10px;max-width:95%}a{color:#145e78}[hidden]{display:none!important}</style>
<header><h1>Listen to p03</h1><p class="yoruba" lang="yo">Kò kúkú sírú ọlọ́run, Ọba tí kò ṣeé pè lẹ́jọ́.</p><p>Listen to each complete recording first. Then listen to one short part at a time and tell us what you hear.</p><p class="muted">The short cuts are rough automatic suggestions. If a cut misses or clips the displayed unit, select “Bad audio cut / boundary”. You do not need to fix it or judge its tone. Human recordings can also receive “No” or “Unsure”.</p><label>Your name or reviewer ID<br><input type="text" id="reviewer" autocomplete="off"></label><p class="muted">Confidence means how sure you are about what you heard and your judgment—not why it sounds that way. High: sure · Medium: some ambiguity · Low: unsure.</p><button id="export" class="primary">Export Review JSON</button><p id="status" role="status">Your draft saves in this browser. Export a copy when finished.</p><details><summary>Expert interface (optional)</summary><p><a href="../p03-supervised-001/index.html" target="_blank">Open the preserved technical alignment interface</a>. It is not required for this listening task.</p></details></header><nav id="recordings" class="tabs" aria-label="Recordings"></nav><main id="main"></main><audio id="segmentAudio" hidden></audio><script id="package" type="application/json">'''+json.dumps(data,ensure_ascii=False).replace('<','\\u003c')+'''</script><script src="review.js"></script></html>'''
 (OUT/'index.html').write_text(html,encoding='utf-8');shutil.copyfile(ROOT/'src/p03_simple_review.js',OUT/'review.js')
 (OUT/'provenance.json').write_text(json.dumps({'source_package_sha256':data['technical_package_sha256'],'source_package':str(SOURCE/'annotation_package.json'),'technical_interface_unchanged':True,'audio_modified':False,'boundary_method':data['seed_method'],'automatic_correctness_scoring':False},indent=2),encoding='utf-8')
 print(OUT)
if __name__=='__main__':main()
