"""Build the resumable, dependency-free Yoruba boundary-review application."""

from __future__ import annotations

import json
import sys
from copy import deepcopy
from pathlib import Path

import numpy as np
import soundfile as sf

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from alignment_repair import repair_sequence  # noqa: E402
from yoruba_orthographic_units import migrate_manual_word_groups  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "alignment/automatic/omnilingual_ctc_training_batch_01.jsonl"
MANUAL = ROOT / "alignment/manual/training_batch_01_manual_corrections.jsonl"
ISSUES = ROOT / "alignment/manual/dataset_item_issues.jsonl"
OUTPUT = ROOT / "alignment/review/yoruba-alignment-review.html"
PROGRESS = ROOT / "alignment/review/review_progress.json"


def read_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [json.loads(line) for line in path.read_text(encoding="utf-8-sig").splitlines() if line.strip()]


def waveform(path: Path, points: int = 720) -> list[float]:
    audio, _ = sf.read(path, dtype="float32")
    if audio.ndim > 1:
        audio = audio.mean(axis=1)
    blocks = np.array_split(audio, points)
    peak = max(float(np.max(np.abs(audio))), 1e-6)
    return [round(float(np.max(np.abs(x))) / peak, 4) if len(x) else 0 for x in blocks]


def main() -> None:
    records = read_jsonl(SOURCE)
    for record in records:
        if record.get("audio_mapping", {}).get("status") == "corrected":
            record["audio_mapping_correction"] = record["audio_mapping"]
        if record.get("audio_path") and (ROOT / record["audio_path"]).exists():
            record["waveform"] = waveform(ROOT / record["audio_path"])
            record["browser_audio_path"] = "../../" + record["audio_path"]
        else:
            record["waveform"] = []
            record["browser_audio_path"] = ""
    latest_manual = {}
    for record in read_jsonl(MANUAL):
        latest_manual[record["prompt_id"]] = record
    latest_issues = {}
    for record in read_jsonl(ISSUES):
        latest_issues[record["prompt_id"]] = record
    automatic_by_id = {record["prompt_id"]: record for record in records}
    # Legacy YT0001 review verified word boundaries before syllable controls
    # existed. Keep its human word times and repair only its displayed automatic
    # syllable suggestions so the current validator can open it safely.
    for prompt_id, manual in list(latest_manual.items()):
        automatic = automatic_by_id[prompt_id]
        prepared = deepcopy(manual)
        if [word.get("text") for word in prepared.get("words", [])] != [word.get("text") for word in automatic.get("words", [])]:
            prepared = migrate_manual_word_groups(prepared, automatic)
            if prepared is None:
                del latest_manual[prompt_id]
                continue
        changed = 0
        for word in prepared.get("words", []):
            syllables, audit = repair_sequence(word.get("syllables", []), float(word["start_s"]), float(word["end_s"]))
            word["syllables"] = syllables
            changed += len(audit)
        if changed:
            prepared["display_boundary_repair"] = {
                "automatic_only": True, "changed_field_count": changed,
                "review_scope_unchanged": prepared.get("review_scope", "word_boundaries_legacy_review"),
            }
        latest_manual[prompt_id] = prepared
    html = TEMPLATE.replace("__DATA__", json.dumps(records, ensure_ascii=False).replace("</", "<\\/"))
    html = html.replace("__SEED__", json.dumps(latest_manual, ensure_ascii=False).replace("</", "<\\/"))
    html = html.replace("__ISSUES__", json.dumps(latest_issues, ensure_ascii=False).replace("</", "<\\/"))
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(html, encoding="utf-8", newline="\n")
    PROGRESS.write_text(json.dumps({
        "schema_version": "0.1", "total": len(records), "imported_verified": len(latest_manual),
        "remaining": len(records) - len(latest_manual) - len(latest_issues), "verified_prompt_ids": sorted(latest_manual),
        "flagged_prompt_ids": sorted(latest_issues),
        "final_dataset_status": "ready" if len(latest_manual) + len(latest_issues) == len(records) else "blocked_pending_human_review",
    }, indent=2) + "\n", encoding="utf-8")
    print(f"built={OUTPUT} records={len(records)} already_imported={len(latest_manual)}")


TEMPLATE = r'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Yoruba Alignment Review</title><style>
:root{--ink:#14213d;--muted:#64748b;--paper:#f8fafc;--card:#fff;--teal:#0f766e;--gold:#f59e0b;--red:#dc2626;--blue:#2563eb}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.45 system-ui,sans-serif}.shell{max-width:1120px;margin:auto;padding:22px}.top,.footer{display:flex;gap:14px;align-items:center;justify-content:space-between}.card{background:var(--card);border:1px solid #dbe3ec;border-radius:14px;padding:17px;margin-top:14px;box-shadow:0 5px 20px #0f172a0d}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.stat{padding:12px;border:1px solid #dbe3ec;border-radius:10px}.stat strong{display:block;font-size:24px}.muted{color:var(--muted)}select,input,textarea,button{font:inherit}select,input,textarea{border:1px solid #cbd5e1;border-radius:8px;padding:7px;background:white}button,.filebtn{border:0;border-radius:9px;padding:9px 13px;background:var(--teal);color:white;font-weight:700;cursor:pointer;display:inline-block}button:disabled{opacity:.45;cursor:not-allowed}button.secondary,.filebtn.secondary{background:#e2e8f0;color:var(--ink)}button.warn{background:#92400e}.controls{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.tracker{display:grid;grid-template-columns:repeat(10,1fr);gap:6px}.track{padding:7px 3px;border:1px solid #cbd5e1;border-radius:7px;background:#fff;color:var(--ink);font-size:12px}.track.verified{background:#ccfbf1;border-color:#0f766e}.track.exported{background:#dbeafe;border-color:#2563eb}.track.flagged{background:#ffedd5;border-color:#c2410c}.track.active{outline:3px solid #f59e0b}canvas{width:100%;height:220px;background:#f8fafc;border-radius:10px;touch-action:none;cursor:crosshair}.transcript{font-size:25px;font-weight:650}.word-grid{display:grid;grid-template-columns:1.3fr .8fr .8fr .8fr;gap:7px;align-items:center}.head{font-size:12px;text-transform:uppercase;color:var(--muted);font-weight:800}.low{color:var(--red);font-weight:700}.ok{color:var(--teal);font-weight:700}.help{border-left:4px solid var(--gold);padding-left:12px}.issue{border-left:4px solid var(--red);padding-left:12px;margin-top:12px}.state{font-weight:700}.hidden{display:none}@media(max-width:680px){.tracker{grid-template-columns:repeat(5,1fr)}.stats{grid-template-columns:1fr}.word-grid{grid-template-columns:1fr .7fr .7fr}.confidence{display:none}.top,.footer{align-items:flex-start;flex-direction:column}}
</style></head><body><main class="shell"><div class="top"><div><h1>Yoruba alignment review</h1><div class="muted">Resumable review for 30 recordings. Automatic and human layers remain separate.</div></div><span class="state" id="currentState"></span></div>
<section class="card stats"><div class="stat"><strong id="verifiedCount">0</strong><span>verified</span></div><div class="stat"><strong id="flaggedCount">0</strong><span>transcript issues</span></div><div class="stat"><strong id="exportedCount">0</strong><span>exported/imported</span></div><div class="stat"><strong id="remainingCount">30</strong><span>remaining</span></div></section>
<section class="card"><div class="tracker" id="tracker"></div><p class="muted">Plain = pending · green = verified · orange = transcript issue · blue = exported/imported</p></section>
<section class="card controls"><button class="secondary" id="prev">← Previous</button><select id="pick"></select><button class="secondary" id="next">Next pending →</button><audio id="audio" controls preload="metadata"></audio></section>
<section class="card"><div class="transcript" id="text"></div><p id="correctionNotice" class="help hidden"></p><p class="muted">Drag a boundary line, edit the times below, or click the waveform to seek.</p><canvas id="wave" width="1000" height="220" aria-label="Waveform with editable word boundaries"></canvas></section>
<section class="card"><h2>Word boundaries</h2><div class="word-grid" id="words"></div></section>
<section class="card"><h2>Syllable boundaries</h2><div class="word-grid" id="syllables"></div></section>
<section class="card"><div class="controls"><label>Reviewer <input id="reviewer" value="Mary Adelua"></label><label>Notes <textarea id="notes" rows="2"></textarea></label></div><p class="help">Mark verified only after checking every word boundary. Changing a verified item returns it to pending.</p><div class="footer"><button class="warn" id="reset">Reset this item</button><button id="verify">Mark verified and continue</button></div></section>
<section class="card"><button class="secondary" id="showIssue">Flag transcript/audio mismatch</button><div id="issuePanel" class="hidden issue"><p id="issueExplanation">Use this when the spoken words differ from the displayed transcript. Do not verify boundaries against incorrect text.</p><label id="observedWrap">Words actually spoken <textarea id="observedTranscript" rows="2"></textarea></label><label>Disposition <select id="issueDisposition"><option value="corrected_transcript_pending_realignment">Correct transcript and re-align</option><option value="exclude_from_dataset">Exclude recording from dataset</option></select></label><label>Issue notes <textarea id="issueNotes" rows="2"></textarea></label><button class="warn" id="saveIssue">Save flag and continue</button></div></section>
<section class="card"><div class="controls"><label class="filebtn secondary">Import earlier JSONL<input class="hidden" id="importFile" type="file" accept=".jsonl,.json"></label><button class="secondary" id="saveProgress">Save progress backup</button><button id="export">Export newly verified JSONL</button></div><p id="status" class="muted">Progress is saved automatically in this browser.</p></section></main>
<script>
function applyDatasetIssueState(r,issue){const missing=r.audio_status==='missing_recording'||!r.browser_audio_path;let notice='';if(missing)notice='No matching recording was found. This item is excluded and cannot be boundary-verified.';else if(r.audio_mapping_correction)notice=`Audio mapping corrected from pre-fix ${r.audio_mapping_correction.source_pre_fix_id}; human re-verification is required.`;else if(r.transcript_correction)notice='The transcript was corrected to the speaker-confirmed audio text and re-aligned.';$('correctionNotice').classList.toggle('hidden',!notice);$('correctionNotice').textContent=notice;if(missing){$('audio').removeAttribute('src');$('audio').load();$('audio').disabled=true}else{$('audio').disabled=false;if($('audio').getAttribute('src')!==r.browser_audio_path)$('audio').src=r.browser_audio_path}$('issueExplanation').textContent=issue?.issue_type==='missing_audio'?'The transcript is retained, but its matching recording is absent. This item is excluded from verified training data.':'Use this when the spoken words differ from the displayed transcript. Do not verify boundaries against incorrect text.';$('observedWrap').classList.toggle('hidden',issue?.issue_type==='missing_audio');$('verify').disabled=!!issue||missing}
const source=__DATA__,seed=__SEED__,issueSeed=__ISSUES__,storageKey='yoruba-alignment-review-v4-transcript-flags',mappingRevision='yt0018-yt0022-offset-fix-v1';let index=0;const $=id=>document.getElementById(id);let state={edits:{},notes:{},verified:{},exportedHashes:{},issues:{},exportedIssueHashes:{},reviewer:'Mary Adelua',mappingRevision:null};
function stableWords(words){return JSON.stringify(words.map(w=>({word_index:w.word_index,text:w.text,start_s:+Number(w.start_s).toFixed(4),end_s:+Number(w.end_s).toFixed(4),syllables:w.syllables||[]})))}function hashText(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16)}function hashWords(words){return hashText(stableWords(words))}function issueHash(issue){return hashText(JSON.stringify({issue_type:issue.issue_type||'transcript_audio_mismatch',observed_transcript_nfc:issue.observed_transcript_nfc||'',disposition:issue.disposition,notes:issue.notes||''}))}function cloneWords(r){return r.words.map(w=>{const start=w.start_s??0,end=w.end_s??Math.min(r.duration_s,.2),raw=w.syllables||[];return{...w,start_s:start,end_s:end,syllables:raw.map((s,i)=>({...s,start_s:s.start_s??start+(end-start)*i/Math.max(1,raw.length),end_s:s.end_s??start+(end-start)*(i+1)/Math.max(1,raw.length)}))}})}
function load(){try{const priorKey='yoruba-alignment-review-v3-unicode-words',saved=JSON.parse(localStorage.getItem(storageKey)||localStorage.getItem(priorKey)||'null');if(saved)state={...state,...saved}}catch(e){}state.issues=state.issues||{};state.exportedIssueHashes=state.exportedIssueHashes||{};if(state.mappingRevision!==mappingRevision){['YT0018','YT0019','YT0020','YT0021','YT0022'].forEach(id=>{delete state.edits[id];delete state.verified[id];delete state.exportedHashes[id]});state.mappingRevision=mappingRevision}source.forEach(r=>{const edit=state.edits[r.prompt_id];if(edit&&edit.map(w=>w.text).join('\u241f')!==r.words.map(w=>w.text).join('\u241f')){delete state.edits[r.prompt_id];delete state.verified[r.prompt_id];delete state.exportedHashes[r.prompt_id]}});Object.values(seed).forEach(row=>{state.edits[row.prompt_id]=row.words;state.notes[row.prompt_id]=row.notes||'';state.verified[row.prompt_id]=true;state.exportedHashes[row.prompt_id]=hashWords(row.words)});Object.values(issueSeed).forEach(row=>{state.issues[row.prompt_id]=row;state.exportedIssueHashes[row.prompt_id]=issueHash(row);delete state.verified[row.prompt_id]});$('reviewer').value=state.reviewer||'Mary Adelua'}function save(){state.reviewer=$('reviewer').value;localStorage.setItem(storageKey,JSON.stringify(state))}function words(){const id=source[index].prompt_id;return state.edits[id]||(state.edits[id]=cloneWords(source[index]))}function isExported(id){return !!state.exportedHashes[id]&&state.exportedHashes[id]===hashWords(state.edits[id]||source.find(r=>r.prompt_id===id).words)}function isIssueExported(id){return !!state.issues[id]&&state.exportedIssueHashes[id]===issueHash(state.issues[id])}
function counts(){const verified=source.filter(r=>state.verified[r.prompt_id]).length,flagged=source.filter(r=>state.issues[r.prompt_id]).length,exported=source.filter(r=>isExported(r.prompt_id)||isIssueExported(r.prompt_id)).length;return{verified,flagged,exported,remaining:source.length-verified-flagged}}
function renderTracker(){const c=counts();$('verifiedCount').textContent=c.verified;$('flaggedCount').textContent=c.flagged;$('exportedCount').textContent=c.exported;$('remainingCount').textContent=c.remaining;$('tracker').innerHTML=source.map((r,i)=>`<button class="track ${state.verified[r.prompt_id]?'verified':''} ${state.issues[r.prompt_id]?'flagged':''} ${(isExported(r.prompt_id)||isIssueExported(r.prompt_id))?'exported':''} ${i===index?'active':''}" data-i="${i}">${r.prompt_id.replace('YT','')}</button>`).join('');document.querySelectorAll('.track').forEach(b=>b.onclick=()=>{index=+b.dataset.i;render()});const id=source[index].prompt_id;$('currentState').textContent=state.issues[id]?'Transcript issue':isExported(id)?'Exported':state.verified[id]?'Verified · awaiting export':'Pending review';$('export').disabled=!source.some(r=>(state.verified[r.prompt_id]&&!isExported(r.prompt_id))||(state.issues[r.prompt_id]&&!isIssueExported(r.prompt_id)))}
function render(){const r=source[index],ws=words(),issue=state.issues[r.prompt_id];$('pick').value=index;$('text').textContent=r.text_nfc;$('audio').src=r.browser_audio_path;$('notes').value=state.notes[r.prompt_id]||'';$('correctionNotice').classList.toggle('hidden',!r.transcript_correction);$('correctionNotice').textContent=r.transcript_correction?`Transcript corrected from “${r.transcript_correction.original_prompt_text_nfc}” to the speaker-confirmed audio text and re-aligned.`:'';$('issuePanel').classList.toggle('hidden',!issue);$('observedTranscript').value=issue?.observed_transcript_nfc||'';$('issueDisposition').value=issue?.disposition||'corrected_transcript_pending_realignment';$('issueNotes').value=issue?.notes||'';$('verify').disabled=!!issue;$('words').innerHTML='<div class="head">Word</div><div class="head">Start</div><div class="head">End</div><div class="head confidence">Auto confidence</div>'+ws.map((w,i)=>`<div>${w.text}</div><input type="number" min="0" max="${r.duration_s}" step="0.01" data-i="${i}" data-k="start_s" value="${Number(w.start_s).toFixed(3)}"><input type="number" min="0" max="${r.duration_s}" step="0.01" data-i="${i}" data-k="end_s" value="${Number(w.end_s).toFixed(3)}"><div class="confidence ${w.confidence<.65?'low':'ok'}">${Math.round(w.confidence*100)}%</div>`).join('');$('syllables').innerHTML='<div class="head">Word · syllable</div><div class="head">Start</div><div class="head">End</div><div class="head confidence">Source</div>'+ws.flatMap((w,wi)=>(w.syllables||[]).map((s,si)=>`<div>${w.text} · ${s.orthographic_form}</div><input type="number" min="${w.start_s}" max="${w.end_s}" step="0.01" data-wi="${wi}" data-si="${si}" data-k="start_s" value="${Number(s.start_s).toFixed(3)}"><input type="number" min="${w.start_s}" max="${w.end_s}" step="0.01" data-wi="${wi}" data-si="${si}" data-k="end_s" value="${Number(s.end_s).toFixed(3)}"><div class="confidence">${s.boundary_source||'manual'}</div>`)).join('');document.querySelectorAll('#words input').forEach(el=>el.onchange=()=>{ws[+el.dataset.i][el.dataset.k]=+el.value;delete state.verified[r.prompt_id];save();render()});document.querySelectorAll('#syllables input').forEach(el=>el.onchange=()=>{ws[+el.dataset.wi].syllables[+el.dataset.si][el.dataset.k]=+el.value;delete state.verified[r.prompt_id];save();render()});renderTracker();draw()}
function draw(){const r=source[index],ws=words(),c=$('wave'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.strokeStyle='#0f766e';x.beginPath();r.waveform.forEach((v,i)=>{const px=i/(r.waveform.length-1)*c.width,h=v*c.height*.42;x.moveTo(px,c.height/2-h);x.lineTo(px,c.height/2+h)});x.stroke();x.font='12px system-ui';ws.forEach((w,i)=>{const px=w.start_s/r.duration_s*c.width;x.strokeStyle='#f59e0b';x.beginPath();x.moveTo(px,0);x.lineTo(px,c.height);x.stroke();x.fillStyle='#14213d';x.fillText(w.text,px+4,16+(i%2)*15)});const last=ws.at(-1);if(last){const px=last.end_s/r.duration_s*c.width;x.strokeStyle='#dc2626';x.beginPath();x.moveTo(px,0);x.lineTo(px,c.height);x.stroke()}}
function nextPending(){for(let step=1;step<=source.length;step++){const i=(index+step)%source.length,id=source[i].prompt_id;if(!state.verified[id]&&!state.issues[id]){index=i;render();return}}index=(index+1)%source.length;render()}let drag=null;$('wave').onpointerdown=e=>{const r=source[index],ws=words(),rect=e.target.getBoundingClientRect(),t=(e.clientX-rect.left)/rect.width*r.duration_s;let best={d:Infinity,i:0,k:'start_s'};ws.forEach((w,i)=>['start_s','end_s'].forEach(k=>{const d=Math.abs(w[k]-t);if(d<best.d)best={d,i,k}}));drag=best;e.target.setPointerCapture(e.pointerId)};$('wave').onpointermove=e=>{if(!drag)return;const r=source[index],rect=e.target.getBoundingClientRect(),t=Math.max(0,Math.min(r.duration_s,(e.clientX-rect.left)/rect.width*r.duration_s));words()[drag.i][drag.k]=+t.toFixed(3);draw()};$('wave').onpointerup=()=>{if(drag){delete state.verified[source[index].prompt_id];drag=null;save();render()}};$('wave').onclick=e=>{if(drag)return;const rect=e.target.getBoundingClientRect();$('audio').currentTime=(e.clientX-rect.left)/rect.width*source[index].duration_s};
$('pick').onchange=e=>{index=+e.target.value;render()};$('prev').onclick=()=>{index=(index+source.length-1)%source.length;render()};$('next').onclick=nextPending;$('notes').onchange=e=>{state.notes[source[index].prompt_id]=e.target.value;save()};$('reviewer').onchange=save;$('showIssue').onclick=()=>$('issuePanel').classList.toggle('hidden');$('saveIssue').onclick=()=>{const r=source[index],observed=$('observedTranscript').value.trim();if(!observed){alert('Enter the words actually spoken.');return}state.issues[r.prompt_id]={schema_version:'0.1',prompt_id:r.prompt_id,review_status:'transcript_audio_mismatch',expected_transcript_nfc:r.text_nfc,observed_transcript_nfc:observed,disposition:$('issueDisposition').value,notes:$('issueNotes').value,reviewer:$('reviewer').value,reviewed_at:new Date().toISOString()};delete state.verified[r.prompt_id];delete state.exportedHashes[r.prompt_id];save();$('status').textContent=`${r.prompt_id} flagged without approving incorrect boundaries.`;nextPending()};$('reset').onclick=()=>{const id=source[index].prompt_id;delete state.edits[id];delete state.notes[id];delete state.verified[id];delete state.exportedHashes[id];delete state.issues[id];delete state.exportedIssueHashes[id];save();render()};$('verify').onclick=()=>{const ws=words(),r=source[index];if(state.issues[r.prompt_id]){alert('Clear the transcript issue before verifying boundaries.');return}let p=0,ok=true;ws.forEach(w=>{if(w.start_s<p||w.end_s<=w.start_s||w.end_s>r.duration_s)ok=false;let sp=w.start_s;(w.syllables||[]).forEach(s=>{if(s.start_s<sp-.001||s.end_s<=s.start_s||s.end_s>w.end_s+.001)ok=false;sp=s.end_s});p=w.end_s});if(!ok){alert('Fix overlapping, reversed, or out-of-range word and syllable times first.');return}state.verified[r.prompt_id]=true;save();$('status').textContent=`${r.prompt_id} verified. Moving to the next pending recording.`;nextPending()};
function recordsToExport(){const now=new Date().toISOString(),rows=source.filter(r=>state.verified[r.prompt_id]&&!isExported(r.prompt_id)).map(r=>({schema_version:'0.1',prompt_id:r.prompt_id,review_status:'human_verified',review_scope:'word_and_syllable_boundaries',reviewer:$('reviewer').value,reviewed_at:now,automatic_alignment_method:r.alignment_method,automatic_alignment_confidence:r.utterance_confidence,notes:state.notes[r.prompt_id]||'',words:state.edits[r.prompt_id]}));source.filter(r=>state.issues[r.prompt_id]&&!isIssueExported(r.prompt_id)).forEach(r=>rows.push(state.issues[r.prompt_id]));return rows}function download(name,text,type='application/jsonl'){const blob=new Blob([text],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}$('export').onclick=()=>{const rows=recordsToExport();if(!rows.length){alert('There are no newly verified, changed, or flagged items to export.');return}download('yoruba-review-records.jsonl',rows.map(x=>JSON.stringify(x)).join('\n')+'\n');rows.forEach(x=>{if(x.review_status==='human_verified')state.exportedHashes[x.prompt_id]=hashWords(x.words);else state.exportedIssueHashes[x.prompt_id]=issueHash(x)});save();$('status').textContent=`Exported ${rows.length} new review record(s). Exact duplicates are now blocked.`;renderTracker()};$('saveProgress').onclick=()=>download('yoruba-alignment-review-progress.json',JSON.stringify({schema_version:'0.1',saved_at:new Date().toISOString(),state},null,2)+'\n','application/json');
$('importFile').onchange=async e=>{const text=await e.target.files[0].text();let rows=[];try{if(text.trim().startsWith('{')&&text.includes('"state"')){const backup=JSON.parse(text);state={...state,...backup.state};rows=[]}else rows=text.split(/\r?\n/).filter(Boolean).map(JSON.parse)}catch(err){alert('This file is not valid review JSONL or a progress backup.');return}for(const row of rows){const r=source.find(x=>x.prompt_id===row.prompt_id);if(!r)continue;if(row.review_status==='human_verified'){state.edits[row.prompt_id]=row.words;state.notes[row.prompt_id]=row.notes||'';state.verified[row.prompt_id]=true;state.exportedHashes[row.prompt_id]=hashWords(row.words);delete state.issues[row.prompt_id]}else if(row.review_status==='transcript_audio_mismatch'){state.issues[row.prompt_id]=row;state.exportedIssueHashes[row.prompt_id]=issueHash(row);delete state.verified[row.prompt_id]}}save();$('status').textContent=`Imported ${rows.length||'saved'} progress record(s).`;render()};
source.forEach((r,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${r.prompt_id} — ${r.text_nfc}`;$('pick').append(o)});load();const firstPending=source.findIndex(r=>!state.verified[r.prompt_id]&&!state.issues[r.prompt_id]);index=firstPending<0?0:firstPending;render();
const renderBeforeDatasetIssueState=render;render=function(){renderBeforeDatasetIssueState();applyDatasetIssueState(source[index],state.issues[source[index].prompt_id])};const drawBeforeMissingAudio=draw;draw=function(){const r=source[index];if(r.waveform.length&&r.duration_s){drawBeforeMissingAudio();return}const c=$('wave'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.fillStyle='#64748b';x.font='16px system-ui';x.fillText('No matching audio recording is available.',24,c.height/2)};render();
</script></body></html>'''

if __name__ == "__main__":
    main()
