"""Render inspectable findings from cross-model outputs; no new acoustic analysis."""
import json,html,hashlib,shutil,collections
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];P=ROOT/'work/slr86/cross-model-comparison-001'
def read(name):return json.loads((P/name).read_text(encoding='utf-8'))
s=read('review_and_acoustic_summary.json');r=read('joined_cross_model.json');rep=read('repeat_consistency.json');diff=read('paired_difference_summary.json')
lines=['Exploratory model comparison — accepted reviews only','', 'Mini-TTS: accepted v2, coral. Realtime 2.1: paired_new_models_001, marin. Natural: six distinct references, not perfect pronunciation standards. One unblinded listener; six sentences, two AI repeats; model, voice and API mode change together. No final scores, training or new recordings.','', 'HUMAN RATINGS (counts of takes; each AI condition has 12)']
for dim in ['lexical_tone_realization','segmental_pronunciation','perceived_nasality','prosody_intonation','rhythm_fluency','overall_yoruba_naturalness','reviewer_confidence']:
 lines.append(dim+': mini-TTS '+str(s['mini_tts']['rating_counts'][dim])+'; Realtime '+str(s['realtime']['rating_counts'][dim]))
lines+=['Natural-reference ratings for those seven dimensions were not collected. Do not impute natural/acceptable labels from transcript QC. All six are transcript matches in natural QC v2.','', 'ISSUE TAGS (optional selections, not exhaustive diagnoses)']
tags=['e/ẹ','o/ọ','s/ṣ','lexical tone','nasal quality','consonant realization','vowel realization','unusual duration/stretching','rhythm','intonation/prosody','other']
for t in tags:lines.append(f"{t}: mini-TTS {s['mini_tts']['issue_tags'].get(t,0)}/12; Realtime {s['realtime']['issue_tags'].get(t,0)}/12")
lines+=['','VERBATIM NOTES']
for c in ['mini_tts','realtime']:
 lines.append(c+': '+(json.dumps(s[c]['notes'],ensure_ascii=False) if s[c]['notes'] else 'No free-text notes supplied.'))
for n in read('natural_reference_observations.json'):
 if n['annotation']['notes']:lines.append('Natural '+n['sentence_id']+' in '+n['session']+' review: '+n['annotation']['notes'])
lines+=['No problematic time intervals were supplied for the AI takes.' if all(not x.get('human_annotation',{}).get('problematic_time_intervals') for x in r) else 'Intervals preserved in joined JSON.','User message observation: Realtime sounded CALMER and LESS LOUD, without meaningful improvement in language-specific quality. Stored separately as a human perception, not an acoustic diagnosis.','','ACOUSTICS']
lines+=['Total file duration: natural 20.309 s (6 recordings); mini-TTS 57.300 s and Realtime 55.050 s (12 each). Natural totals are not exposure-matched to twice as many AI files. AI total difference is -2.250 s (-3.9%).','The following table gives medians across recordings, not pooled frames. The separate paired-difference table averages the two takes per sentence before subtracting model conditions; its medians need not equal differences of clip medians.','metric | natural | mini-TTS | Realtime']
keys=['duration_s','whole_rms_dbfs','active_above_40_rms_dbfs','active_above_40_s','pyin_voiced_duration_proxy_s','pyin_median_hz','praat_median_hz','pyin_min_hz','pyin_max_hz','praat_min_hz','praat_max_hz','pyin_relative_width90_st','pyin_voiced_percent','praat_native_voiced_percent','voiced_runs_per_second','voiced_run_median_s','unvoiced_run_max_s','median_adjacent_voiced_step_st','pitch_disagreement_median_st','voicing_disagreement_percent','agreement_screen_percent','crest_factor_db','active_block_rms_width90_db']
for k in keys:lines.append(k+' | '+' | '.join(f"{s[c]['clip_metric_distributions'][k]['median']:.3f}" for c in ['natural','mini_tts','realtime']))
lines+=['Median minima/maxima above summarize per-file raw ranges; exact min/max and 5th/95th percentiles for every clip are in cross_model_acoustics.csv. Raw extremes can include estimator failures. Pitch is preserved in Hz and in own-utterance-relative semitones, separately per estimator.','Verified speaking duration is unavailable: voiced duration excludes unvoiced consonants, and RMS gates may include background noise or miss quiet speech. File duration includes silence. Threshold sensitivity at -50/-40/-30 dBFS is retained; these are energy proxies, not a validated speech detector.','dBFS is digital amplitude relative to full scale, not calibrated sound pressure, vocal effort, or perceptual loudness. Recordings were not normalized or trimmed. Natural recording channels and speakers differ.','','CALMER / LESS LOUD: EVIDENCE CHECK','Realtime had HIGHER whole-file RMS in all six sentence averages. Median paired increase: +4.30 dB. At -50/-40/-30 dBFS activity gates, all six sentence averages also had higher gated RMS; median increases were +4.34/+4.13/+3.32 dB. Thus lower digital signal level is not supported. No playback-volume measurement or frequency-weighted loudness calibration was available. Spectral balance, voice quality or playback conditions could affect perception; these explanations are untested.','Lower pitch is a plausible correlate of perceived calmer style: Realtime median F0 was lower in 5/6 sentence averages with pYIN, 4/6 with Praat. Median paired deltas: -15.73 Hz and -12.00 Hz. This is confounded by marin versus coral and is not a pronunciation improvement.','No consistent slower timing or narrower expressive range: file duration was lower for 4/6 sentence averages; energy-active duration and voiced-duration proxies each lower in only 3/6. Relative pitch-width changes were mixed (3/6 lower). Active-block RMS dynamic width was lower in only 1/6. Crest factor changed little and inconsistently. We cannot quantify calmness from these observations.','','REPEAT CONSISTENCY']
for c in ['mini_tts','realtime']:
 rr=[x for x in rep if x['condition']==c]
 lines.append(c+' same-rating sentence pairs: '+str({k:sum(x['rating_agreement'][k] for x in rr) for k in rr[0]['rating_agreement']}))
 for k in ['duration_s','whole_rms_dbfs','pyin_median_hz','pyin_relative_width90_st']:
  vals=sorted(x['absolute_metric_differences'][k] for x in rr);lines.append(c+' median absolute take-to-take '+k+': '+str(round((vals[2]+vals[3])/2,3)))
lines+=['Realtime repeats were more consistent on these four selected descriptors in this sample; this does not imply better language quality. Two repeats cannot characterize a generation distribution.','','RELIABILITY','Median per-clip pYIN/Praat voicing disagreement: 14.25% mini-TTS versus 22.60% Realtime; all six sentence-average disagreements increased. Jointly voiced-frame median pitch disagreement remained small (0.183 vs 0.174 semitones), but this omits frames where the estimators disagree about voicing.']
for c in ['mini_tts','realtime']:lines.append(c+' frame flags (overlap allowed): '+str(s[c]['flag_frame_counts']))
lines+=['Do not treat the agreement screen as an accuracy guarantee. Both estimators can fail together; many frames fail probability/strength screens. Raw measurements and original flags remain linked in provenance.','','DECISIONS','1. No broad material Yoruba-quality improvement is established by this pilot. Realtime has small category shifts: tone 3/12 somewhat unnatural, segmental 3/12, prosody 2/12, rhythm 1/12; overall 1/12 noticeably unnatural and 11/12 very unnatural. No natural/acceptable AI ratings. The clearest limited contrast is p03 repeat 2; preserve it without claiming a validated effect.','2. Acoustic style changed: higher digital RMS, generally lower median pitch, modestly shorter files and more consistent selected repeat descriptors. Differences are model-plus-voice-plus-endpoint effects.','3. Lower median F0 is most consistent with calmer; repeat consistency is supporting descriptive context rather than proof of calmness within a take. Lower RMS, uniformly slower delivery and uniformly narrower pitch dynamics are not supported.','4. Tone, consonant/vowel realization, intonation and rhythm problems persisted across both conditions. Nasality severity labels shifted, but two Realtime takes were cannot determine, and ratings do not establish acoustic nasality.','5. Variation now supports exploratory candidate-feature hypotheses and selecting contrasts, not training or validating predictors. Tone/segmental each have only three milder examples, prosody two, rhythm/naturalness one; these cluster by sentence and condition. Natural clips lack comparable dimension ratings, so cannot be silently used as positive labels.','6. Lexical tone needs verified tone-bearing-unit boundaries and context-sensitive relative contours. Segmental pronunciation needs verified phoneme/segment labels, vowel/formant/spectral and duration features. Nasality needs exploratory harmonic/formant measures, F1 bandwidth and spectral trajectories with controls. Prosody and rhythm need phrase boundaries, syllable timing and verified pauses; naturalness needs broader independent listener labels and perceptual controls.','7. Smallest useful next experiment: use existing p03 natural audio plus both mini-TTS and both Realtime takes. Collect supervised phrase/syllable boundaries and localized native-listener issue labels, targeting the milder Realtime repeat 2. If investigating loudness perception separately, plan a counterbalanced original-versus-level-matched listening control using derived copies only after approval; keep raw originals intact. No experiment was executed here.']
(P/'findings.txt').write_text('\n'.join(lines)+'\n',encoding='utf-8')
(P/'report.html').write_text('<!doctype html><meta charset="utf-8"><title>Exploratory model comparison</title><style>body{font:17px system-ui;max-width:1150px;margin:auto;padding:25px}pre{white-space:pre-wrap;line-height:1.6}img{width:100%}</style><h1>Exploratory model comparison</h1><img src="style_comparison.png"><img src="repeat_consistency.png"><pre>'+html.escape('\n'.join(lines))+'</pre>',encoding='utf-8')
shutil.copyfile(Path(__file__),P/'versions'/Path(__file__).name)
# All linked analysis inputs remain unchanged after this read-only measurement/report pass.
prov=read('provenance.json');assert all(hashlib.sha256(Path(x['path']).read_bytes()).hexdigest()==x['sha256'] for x in prov['input_hashes'])
prov['source_hashes']={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in (P/'versions').iterdir()};(P/'provenance.json').write_text(json.dumps(prov,ensure_ascii=False,indent=2),encoding='utf-8')
print('Saved complete findings/report; verified all input hashes unchanged.')
