'use strict';
const packageData=JSON.parse(document.getElementById('data').textContent),records=packageData.records;
const storageKey='p03-supervised-001:'+records.map(r=>r.audio_sha256).join(':');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const median=a=>{a=a.filter(v=>v!==null&&Number.isFinite(v)).sort((a,b)=>a-b);return a.length?(a[Math.floor(a.length/2)]+a[Math.floor((a.length-1)/2)])/2:null};
const fmt=x=>x===null?'—':Number(x).toFixed(3);
let selected=0,stopTimer=null,editLog=[];
function validate(r){let end=0;for(const s of r.segments){if(!Number.isFinite(s.start_s)||!Number.isFinite(s.end_s)||s.start_s<end||s.end_s<=s.start_s||s.end_s>r.duration_s)throw Error(r.id+': intervals must be ordered, nonoverlapping, and inside the recording.');if(s.boundary_review==='confirmed'&&(!s.written_unit.trim()||!s.confidence))throw Error('Confirmed interval needs written unit and confidence.');if(s.tone_review==='confirmed'&&!s.expected_orthographic_tone)throw Error('Confirmed reference tone cannot be empty.');if(s.expected_orthographic_tone&&!/^[HML]+$/.test(s.expected_orthographic_tone))throw Error('Expected tone must use H/M/L or remain blank.');end=s.end_s;}}
function measurements(r,s){const frames=r.frames.filter(f=>s.start_s<=f.timestamp_s&&f.timestamp_s<s.end_s),spectral=r.spectral_frames.filter(f=>s.start_s<=f.timestamp_s&&f.timestamp_s<s.end_s),praat=r.praat_native_frames.filter(f=>s.start_s<=f.timestamp_s&&f.timestamp_s<s.end_s);const flags={};frames.forEach(f=>(f.flags||'').split('|').filter(Boolean).forEach(k=>flags[k]=(flags[k]||0)+1));const contained=frames.filter(f=>f.window_start_s>=s.start_s&&f.window_end_s<=s.end_s);const reliable=contained.filter(f=>f.agreement_screen_pass);return {duration_s:s.end_s-s.start_s,frame_assignment:'Timestamp-in-interval; window overlap preserved. Screened summary uses fully contained windows only.',frames:frames.map(f=>({...f,segment_time_s:f.timestamp_s-s.start_s,window_crosses_segment_boundary:f.window_start_s<s.start_s||f.window_end_s>s.end_s})),praat_native_frames:praat.map(f=>({...f,segment_time_s:f.timestamp_s-s.start_s})),spectral_frames:spectral.map(f=>({...f,segment_time_s:f.timestamp_s-s.start_s,window_crosses_segment_boundary:f.window_start_s<s.start_s||f.window_end_s>s.end_s})),summary:{pyin_median_hz:median(frames.map(f=>f.f0_hz)),praat_median_hz:median(frames.map(f=>f.praat_f0_hz)),pyin_relative_median_st:median(frames.map(f=>f.relative_pitch_semitones)),praat_relative_median_st:median(frames.map(f=>f.praat_relative_semitones)),screened_contained_pyin_median_hz:median(reliable.map(f=>f.f0_hz)),screened_contained_frames:reliable.length,total_frames:frames.length,window_crossing_frames:frames.length-contained.length,pitch_disagreement_median_st:median(frames.map(f=>f.signed_difference_semitones===null?null:Math.abs(f.signed_difference_semitones))),voicing_disagreement_frames:frames.filter(f=>f.praat_voiced!==null&&f.voiced!==f.praat_voiced).length,rms_dbfs:median(spectral.map(f=>f.rms_dbfs)),spectral_centroid_hz:median(spectral.map(f=>f.spectral_centroid_hz)),spectral_rolloff85_hz:median(spectral.map(f=>f.spectral_rolloff85_hz)),high_low_band_power_db:median(spectral.map(f=>f.high_low_band_power_db)),spectral_window_crossings:spectral.filter(f=>f.window_start_s<s.start_s||f.window_end_s>s.end_s).length,flags}};}
function save(){try{localStorage.setItem(storageKey,JSON.stringify({reviewer:document.getElementById('reviewer').value,records:records.map(r=>({id:r.id,segments:r.segments})),editLog}));document.getElementById('status').textContent='Draft saved: '+records.reduce((n,r)=>n+r.segments.filter(s=>s.boundary_review==='confirmed').length,0)+' boundaries confirmed; export to keep a portable copy.';}catch{document.getElementById('status').textContent='Autosave unavailable; export before closing.'}}
try{const draft=JSON.parse(localStorage.getItem(storageKey)||'null');if(draft){document.getElementById('reviewer').value=draft.reviewer||'';draft.records.forEach(x=>{const r=records.find(r=>r.id===x.id);if(r)r.segments=x.segments;});editLog=draft.editLog||[];}}catch{}
function plot(r){const x=t=>55+t/r.duration_s*1325;let svg='<text x="2" y="16">Wave</text><text x="2" y="140">Hz</text><text x="2" y="290">st</text>';for(const h of [100,200,300,400,500])svg+=`<text x="2" y="${270-(h-65)/435*125}" font-size="10">${h}</text>`;for(const st of [-15,0,15])svg+=`<text x="2" y="${347-st*3}" font-size="10">${st}</text>`;
 svg+=r.waveform.map(v=>`<line x1="${x(v[0])}" x2="${x(v[0])}" y1="${75-v[1]*65}" y2="${75-v[2]*65}" stroke="#444"/>`).join('');
 for(const [key,color,fy] of [['f0_hz','#1675bd',v=>270-(v-65)/435*125],['praat_f0_hz','#d4770c',v=>270-(v-65)/435*125],['relative_pitch_semitones','#1675bd',v=>347-v*3],['praat_relative_semitones','#d4770c',v=>347-v*3]])svg+=r.frames.filter(f=>f[key]!==null).map(f=>`<circle cx="${x(f.timestamp_s)}" cy="${fy(f[key])}" r="1.4" fill="${color}"/>`).join('');
 for(const [i,s] of r.segments.entries()){for(const t of [s.start_s,s.end_s])svg+=`<line x1="${x(t)}" x2="${x(t)}" y1="18" y2="400" stroke="${s.boundary_review==='confirmed'?'#16804a':'#888'}" stroke-dasharray="4"/>`;svg+=`<text x="${x((s.start_s+s.end_s)/2)}" y="17" text-anchor="middle" font-size="11">${i+1}</text>`;}
 for(let t=0;t<=r.duration_s;t+=.5)svg+=`<text x="${x(t)}" y="422" font-size="11">${t.toFixed(1)}</text>`;document.querySelector('svg').innerHTML=svg;}
function render(){clearTimeout(stopTimer);const r=records[selected];document.getElementById('main').innerHTML=`<h2>${esc(r.id)}</h2><audio id="audio" controls preload="metadata" src="${esc(r.audio_url)}"></audio><p>Original duration ${fmt(r.duration_s)} s · no audio processing · blue pYIN / orange Praat; numbered boundaries refer to rows.</p><details><summary>Model / voice / source provenance</summary><pre>${esc(JSON.stringify(r.provenance,null,2))}</pre></details><svg viewBox="0 0 1400 430"></svg><details><summary>Spectrogram and spectral-method limitations</summary><p>${esc(packageData.spectral_method)}</p><img src="${esc(r.spectrogram_url)}"></details><p>Play an interval with context, pause at a boundary, then use “Use cursor”. Split inserts two intervals; merge joins this row and the next. Edit text/tone labels as needed. Empty tone means unresolved. Changing text or timing clears verification.</p><div class="scroll"><table><thead><tr><th># / reference</th><th>Start / end (seconds)</th><th>Listen / structure</th><th>Verification</th><th>Notes</th><th>Measurements / uncertainty</th></tr></thead><tbody>${r.segments.map((s,i)=>`<tr data-row="${i}"><td>${i+1}<br><input class="unit" data-key="written_unit" value="${esc(s.written_unit)}" aria-label="Written unit ${i+1}"><br><input class="tone" data-key="expected_orthographic_tone" value="${esc(s.expected_orthographic_tone)}" aria-label="Expected tone ${i+1}"><small> H/M/L reference</small></td><td><input type="number" min="0" max="${r.duration_s}" step="0.001" data-key="start_s" value="${s.start_s}" aria-label="Start ${i+1}"><button data-action="start">Use cursor</button><br><input type="number" min="0" max="${r.duration_s}" step="0.001" data-key="end_s" value="${s.end_s}" aria-label="End ${i+1}"><button data-action="end">Use cursor</button></td><td><button data-action="play">Play interval</button><button data-action="context">Play + context</button><br><button data-action="split">Split at cursor</button><button data-action="merge">Merge next</button></td><td><label>Boundary <select data-key="boundary_review">${['unverified','confirmed','uncertain'].map(v=>`<option ${s.boundary_review===v?'selected':''}>${v}</option>`).join('')}</select></label><br><label>Reference tone <select data-key="tone_review">${['unverified','confirmed','uncertain'].map(v=>`<option ${s.tone_review===v?'selected':''}>${v}</option>`).join('')}</select></label><br><select data-key="confidence"><option value="">Confidence</option>${['low','medium','high'].map(v=>`<option ${s.confidence===v?'selected':''}>${v}</option>`).join('')}</select></td><td><textarea data-key="notes" aria-label="Notes ${i+1}">${esc(s.notes)}</textarea></td><td class="metrics" data-metrics="${i}"></td></tr>`).join('')}</tbody></table></div>`;plot(r);updateStats(r);}
function updateStats(r){for(const [i,s] of r.segments.entries()){const m=measurements(r,s).summary;document.querySelector(`[data-metrics="${i}"]`).innerHTML=`${fmt(s.end_s-s.start_s)} s; F0 Hz pYIN ${fmt(m.pyin_median_hz)} / Praat ${fmt(m.praat_median_hz)}<br>Relative st ${fmt(m.pyin_relative_median_st)} / ${fmt(m.praat_relative_median_st)}<br>Contained screened frames ${m.screened_contained_frames}/${m.total_frames}; window crossings ${m.window_crossing_frames}<br>Pitch disagreement ${fmt(m.pitch_disagreement_median_st)} st; voicing disagreements ${m.voicing_disagreement_frames}<br>RMS ${fmt(m.rms_dbfs)} dBFS; centroid ${fmt(m.spectral_centroid_hz)} Hz; rolloff ${fmt(m.spectral_rolloff85_hz)} Hz; high/low ${fmt(m.high_low_band_power_db)} dB<br><small>Spectral crossings ${m.spectral_window_crossings}; ${esc(JSON.stringify(m.flags))}</small>`;}}
function changed(s){s.boundary_review='unverified';s.tone_review='unverified';s.modified_at=new Date().toISOString();}
document.getElementById('main').addEventListener('change',e=>{const row=e.target.closest('[data-row]');if(!row||!e.target.dataset.key)return;const r=records[selected],s=r.segments[Number(row.dataset.row)],key=e.target.dataset.key;const before=JSON.parse(JSON.stringify(s));s[key]=['start_s','end_s'].includes(key)?(e.target.value===''?null:Number(e.target.value)):e.target.value;if(['start_s','end_s','written_unit','expected_orthographic_tone'].includes(key))changed(s);s.modified_at=new Date().toISOString();editLog.push({recording:r.id,action:'edit',key,before,after:JSON.parse(JSON.stringify(s)),at:s.modified_at});save();const time=document.getElementById('audio').currentTime;render();document.getElementById('audio').currentTime=time;});
document.getElementById('main').addEventListener('click',e=>{const action=e.target.dataset.action,row=e.target.closest('[data-row]');if(!action||!row)return;const r=records[selected],i=Number(row.dataset.row),s=r.segments[i],audio=document.getElementById('audio'),cursor=audio.currentTime;try{if(action==='play'||action==='context'){if(!Number.isFinite(s.start_s)||!Number.isFinite(s.end_s)||s.end_s<=s.start_s)throw Error('Set a valid interval first.');clearTimeout(stopTimer);audio.pause();const pad=action==='context'?.15:0,a=Math.max(0,s.start_s-pad),b=Math.min(r.duration_s,s.end_s+pad);audio.currentTime=a;audio.play().then(()=>{stopTimer=setInterval(()=>{if(audio.currentTime>=b||audio.ended){audio.pause();clearInterval(stopTimer)}},15)});return;}
 const before=JSON.parse(JSON.stringify(r.segments));audio.pause();clearTimeout(stopTimer);
 if(action==='start'||action==='end'){s[action+'_s']=Number(cursor.toFixed(4));changed(s);}
 if(action==='split'){if(!(s.start_s<cursor&&cursor<s.end_s))throw Error('Pause the cursor inside this interval before splitting.');const left={...s,end_s:Number(cursor.toFixed(4))},right={...s,id:s.id+'_split_'+Date.now(),start_s:Number(cursor.toFixed(4)),written_unit:'',expected_orthographic_tone:'',notes:'Assign written unit and expected tone after splitting.'};changed(left);changed(right);r.segments.splice(i,1,left,right);}
 if(action==='merge'){if(i+1>=r.segments.length)throw Error('No following interval.');const b=r.segments[i+1];const merged={...s,end_s:b.end_s,written_unit:s.written_unit+b.written_unit,expected_orthographic_tone:s.expected_orthographic_tone&&b.expected_orthographic_tone?s.expected_orthographic_tone+b.expected_orthographic_tone:'',reference_ids:[...new Set([...s.reference_ids,...b.reference_ids])],notes:[s.notes,b.notes].filter(Boolean).join(' | ')};changed(merged);r.segments.splice(i,2,merged);}
 editLog.push({recording:r.id,action,before,after:JSON.parse(JSON.stringify(r.segments)),at:new Date().toISOString()});save();render();document.getElementById('audio').currentTime=cursor;}catch(err){document.getElementById('status').textContent=err.message;}});
const selector=document.getElementById('recording');records.forEach((r,i)=>{const o=document.createElement('option');o.value=i;o.textContent=r.id;selector.appendChild(o)});selector.onchange=()=>{document.getElementById('audio')?.pause();selected=Number(selector.value);render();};document.getElementById('reviewer').oninput=save;
document.getElementById('export').onclick=()=>{try{records.forEach(validate);const reviewer=document.getElementById('reviewer').value.trim();if(!reviewer)throw Error('Enter reviewer identifier.');const output={...packageData,reviewer,exported_at:new Date().toISOString(),editLog,records:records.map(r=>({...r,segments:r.segments.map(s=>({...s,duration_s:s.end_s-s.start_s,measurement_status:s.boundary_review==='confirmed'?'HUMAN_BOUNDARY_CONFIRMED_NOT_CORRECTNESS':'PROVISIONAL',acoustic_measurements:measurements(r,s)}))}))};save();const url=URL.createObjectURL(new Blob([JSON.stringify(output,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='p03_supervised_interval_review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.getElementById('status').textContent='Exported. Unverified intervals remain provisional; no correctness inference.';}catch(err){document.getElementById('status').textContent=err.message}};render();
