'use strict';
const pkg=JSON.parse(document.getElementById('package').textContent),key='p03-simple-listening-001:'+pkg.technical_package_sha256;
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names=['Natural human reference','mini-TTS · take 1','mini-TTS · take 2','Realtime 2.1 · take 1','Realtime 2.1 · take 2'];
let state={reviewer:'',recordings:pkg.records.map(r=>({id:r.id,full_sentence_listened:false,full_sentence_listened_at:null,segment_index:0,answers:r.segments.map(s=>({segment_id:s.id,matches_unit:null,lexical_tone:null,pronunciation_issues:[],bad_audio_cut:false,note:'',confidence:null,annotation_timestamp:null,segment_play_count:0}))}))},recordIndex=0,timer=null;
try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&saved.recordings.length===5&&saved.recordings.every((r,i)=>r.id===pkg.records[i].id&&r.answers.length===pkg.records[i].segments.length))state=saved;}catch{}
const player=document.getElementById('segmentAudio');document.getElementById('reviewer').value=state.reviewer;
function save(){state.reviewer=document.getElementById('reviewer').value;try{localStorage.setItem(key,JSON.stringify(state));document.getElementById('status').textContent='Draft saved. Export Review JSON to keep a portable copy.';}catch{document.getElementById('status').textContent='Autosave unavailable. Keep this page open and export your review.'}}
function stop(){clearInterval(timer);player.pause();document.getElementById('fullAudio')?.pause();}
function choices(field,values,value){return `<fieldset><legend>${field==='matches_unit'?'Does this part sound like the displayed Yorùbá unit?':field==='lexical_tone'?'Does its lexical tone sound correct?':'How confident are you?'}</legend><div class="choices">${values.map(v=>`<label class="choice"><input type="radio" name="${field}" value="${v}" ${value===v?'checked':''}> ${v}</label>`).join('')}</div></fieldset>`;}
function render(){stop();const r=pkg.records[recordIndex],draft=state.recordings[recordIndex],i=draft.segment_index,s=r.segments[i],a=draft.answers[i];
 document.getElementById('recordings').innerHTML=names.map((n,j)=>`<button data-record="${j}" aria-pressed="${j===recordIndex}">${n}</button>`).join('');
 document.getElementById('main').innerHTML=`<article><h2>${names[recordIndex]}</h2><p><strong>1. Listen to the complete sentence</strong></p><audio id="fullAudio" controls preload="metadata" src="${escapeHTML(r.audio_url)}"></audio><p class="muted" id="fullStatus">${draft.full_sentence_listened?'Complete sentence listened to. You can replay it at any time.':'Play the sentence through to the end to begin the short-part review.'}</p><section id="segments" ${draft.full_sentence_listened?'':'hidden'}><hr><p><strong>2. Listen to this short part</strong> · ${i+1} of ${r.segments.length}</p><p class="yoruba" lang="yo">${escapeHTML(s.written_unit)}</p><p class="muted">From the written word: <span lang="yo">${escapeHTML(s.word)}</span></p><button id="playPart" class="primary">▶ Play this part</button><p id="playStatus" class="muted" role="status">${a.segment_play_count?'You can replay this part as often as needed.':'Listen before answering.'}</p><label class="cut"><input id="badCut" type="checkbox" ${a.bad_audio_cut?'checked':''}> Bad audio cut / boundary</label><div id="judgments" ${a.bad_audio_cut?'hidden':''}>${choices('matches_unit',['Yes','No','Unsure'],a.matches_unit)}${choices('lexical_tone',['Yes','No','Unsure'],a.lexical_tone)}<fieldset><legend>If pronunciation sounds wrong, what seems wrong? (optional)</legend><div class="choices">${['Vowel','Consonant','Other'].map(v=>`<label class="choice"><input type="checkbox" data-issue="${v}" ${a.pronunciation_issues.includes(v)?'checked':''}> ${v}</label>`).join('')}</div></fieldset></div><p id="cutMessage" class="muted" ${a.bad_audio_cut?'':'hidden'}>Flagged for later technical correction. You can skip the sound and tone questions; no linguistic conclusion will be drawn from this cut.</p><label>Optional note<textarea id="note">${escapeHTML(a.note)}</textarea></label>${choices('confidence',['High','Medium','Low'],a.confidence)}<div class="navigation"><button id="prev" ${i===0?'disabled':''}>Previous part</button><button id="next">${i===r.segments.length-1?'Next recording':'Next part'}</button></div><p class="muted">You may leave questions blank or choose Unsure. No automatic correctness score is calculated.</p></section></article>`;
 const full=document.getElementById('fullAudio');full.addEventListener('play',()=>{clearInterval(timer);player.pause();});full.addEventListener('ended',()=>{draft.full_sentence_listened=true;draft.full_sentence_listened_at=new Date().toISOString();document.getElementById('segments').hidden=false;document.getElementById('fullStatus').textContent='Complete sentence listened to. You can replay it at any time.';save();});
 document.getElementById('playPart').onclick=async()=>{stop();player.src=r.audio_url;player.currentTime=s.start_s;try{await player.play();a.segment_play_count++;save();document.getElementById('playStatus').textContent='Playing this part…';timer=setInterval(()=>{if(player.currentTime>=s.end_s||player.ended){player.pause();clearInterval(timer);document.getElementById('playStatus').textContent='Playback finished. Replay if needed.'}},15);}catch{document.getElementById('playStatus').textContent='Playback failed. Try again; do not judge an unheard segment.'}};
 document.getElementById('prev').onclick=()=>{draft.segment_index--;save();render()};document.getElementById('next').onclick=()=>{if(i<r.segments.length-1)draft.segment_index++;else if(recordIndex<4)recordIndex++;else document.getElementById('status').textContent='You reached the last recording. Export your review when ready.';save();render()};
 document.getElementById('badCut').onchange=e=>{a.bad_audio_cut=e.target.checked;a.annotation_timestamp=new Date().toISOString();document.getElementById('judgments').hidden=a.bad_audio_cut;document.getElementById('cutMessage').hidden=!a.bad_audio_cut;save()};
 document.getElementById('note').oninput=e=>{a.note=e.target.value;a.annotation_timestamp=new Date().toISOString();save()};
 document.querySelectorAll('input[type=radio]').forEach(e=>e.onchange=()=>{a[e.name]=e.value;a.annotation_timestamp=new Date().toISOString();save()});document.querySelectorAll('[data-issue]').forEach(e=>e.onchange=()=>{a.pronunciation_issues=[...document.querySelectorAll('[data-issue]:checked')].map(x=>x.dataset.issue);a.annotation_timestamp=new Date().toISOString();save()});
}
document.getElementById('recordings').onclick=e=>{if(e.target.dataset.record!==undefined){recordIndex=Number(e.target.dataset.record);render()}};document.getElementById('reviewer').oninput=save;
document.getElementById('export').onclick=()=>{save();if(!state.reviewer.trim()){document.getElementById('status').textContent='Enter your reviewer ID before exporting.';return;}const output={schema_version:'p03-simple-listening-1.0',review_session_id:'p03-listening-001',reviewer:state.reviewer,exported_at:new Date().toISOString(),evidence_type:'human_perceptual_judgments_not_automatic_scores',automatic_scoring:false,technical_package_path:pkg.technical_package_path,technical_package_sha256:pkg.technical_package_sha256,normalization:pkg.normalization,spectral_method:pkg.spectral_method,records:state.recordings.map((d,j)=>{const r=pkg.records[j];return {recording_id:r.id,audio_sha256:r.audio_sha256,provenance:r.provenance,full_sentence_listened:d.full_sentence_listened,full_sentence_listened_at:d.full_sentence_listened_at,segments:d.answers.map((a,i)=>{const s=r.segments[i];return {...a,written_unit:s.written_unit,reference_word:s.word,expected_orthographic_tone:s.expected_orthographic_tone,automatic_interval:{start_s:s.start_s,end_s:s.end_s,duration_s:s.end_s-s.start_s,status:'UNVERIFIED_PROPOSAL'},technical_correction_required:a.bad_audio_cut,linguistic_interpretation_eligible:!a.bad_audio_cut&&d.full_sentence_listened&&a.segment_play_count>0,acoustic_measurements:{frames:r.frames.filter(f=>s.start_s<=f.timestamp_s&&f.timestamp_s<s.end_s),praat_native_frames:r.praat_native_frames.filter(f=>s.start_s<=f.timestamp_s&&f.timestamp_s<s.end_s),spectral_frames:r.spectral_frames.filter(f=>s.start_s<=f.timestamp_s&&f.timestamp_s<s.end_s)}};})};})};const url=URL.createObjectURL(new Blob([JSON.stringify(output,null,2)],{type:'application/json;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='p03_simple_listening_review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.getElementById('status').textContent='Review exported. Blank answers remain blank; bad cuts are flagged for technical correction.';};render();
